---
:verbose: false

:queues:
  # The default queue for all application jobs that don't have a specific queue.
  - default

  # The default queue for ActionMailer classes.
  - mailers

  # ActionMailbox queues. See `ActionMailbox.queues`.
  - action_mailbox_routing
  - action_mailbox_incineration

  # ActiveStorage queues. See `ActiveStorage.queues`.
  - active_storage_analysis
  - active_storage_purge
